name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.3

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        
    - name: Install webmock
      run: |
        gem install webmock -v '3.14'

    - name: Database Setup
      run: |
        bundle exec rake db:create db:migrate

    - name: Run RSpec Tests
      run: bundle exec rspec